### ISSUE TITLE
Support to hubot-slack adapter

### ISSUE THREAD

**Issue by dfleury** [b3nj4m/hubot-react#8]
Apparently, there is a problem when using it with slack plataform...
See above:
```
> jbot react saboutage kill them all!
```
```
TypeError: Cannot read property 'saboutage' of null
  at addResponse (/app/node_modules/hubot-react/scripts/react.js:136:43)
  at TextListener.callback (/app/node_modules/hubot-react/scripts/react.js:271:23)
  at executeListener (/app/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/app/node_modules/hubot/src/middleware.coffee:41:37, <js>:32:16)
  at /app/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/app/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/app/node_modules/async/lib/async.js:268:15)
  at /app/node_modules/hubot/src/middleware.coffee:46:7, <js>:35:22
  at process._tickCallback (node.js:355:11)
```
Versions:
```
"hubot": "2.16.0",
"hubot-slack": "3.3.0",
"hubot-react": "4.1.1"
```

**Comment by MrMMorris** [comment]
This would be super neat!
